# Generated by Django 5.0.3 on 2024-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='Debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Debet'),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='Free_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Wolne środki'),
        ),
    ]
