# Generated by Django 5.0.3 on 2024-04-21 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0003_alter_accountmodel_debit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='Value_operation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Wartość operacji'),
        ),
    ]
