# Generated by Django 5.0.3 on 2024-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0004_alter_operationmodel_value_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='Number_IBAN',
            field=models.CharField(blank=True, max_length=28, verbose_name='Nr IBAN'),
        ),
    ]
