# Generated by Django 5.0.3 on 2024-04-22 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0005_alter_accountmodel_number_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='Debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Debet'),
        ),
    ]
