# Generated by Django 5.0.3 on 2024-04-22 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0006_alter_accountmodel_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='Debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Debet'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='Free_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Wolne środki'),
        ),
    ]
