# Generated by Django 5.0.3 on 2024-04-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0008_alter_operationmodel_value_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='Created_employee',
            field=models.CharField(max_length=50, verbose_name='Pracownik'),
        ),
        migrations.AlterField(
            model_name='accounttypemodel',
            name='Description',
            field=models.CharField(max_length=100, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Address',
            field=models.CharField(max_length=100, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Birth_city',
            field=models.CharField(max_length=100, verbose_name='Miejsce urodzenia'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='City',
            field=models.CharField(max_length=100, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Created_employee',
            field=models.CharField(max_length=50, verbose_name='Pracownik'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='First_name',
            field=models.CharField(max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Last_name',
            field=models.CharField(max_length=100, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='Operation_employee',
            field=models.CharField(max_length=50, verbose_name='Pracownik'),
        ),
    ]
