# Generated by Django 5.0.3 on 2024-04-30 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0009_alter_accountmodel_created_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='Created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='Created_employee',
            field=models.CharField(max_length=50, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='Debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Debit'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='Free_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Free balance'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='Id_account',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id account'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='Number_IBAN',
            field=models.CharField(blank=True, max_length=28, verbose_name='IBAN number'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='Percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percent'),
        ),
        migrations.AlterField(
            model_name='accounttypemodel',
            name='Description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='accounttypemodel',
            name='Id_account_type',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Identyfikator rachunku - poprawny format: A-00', regex='^[a-zA-Z]{1}-[0-9]{2}$')], verbose_name='Id account type'),
        ),
        migrations.AlterField(
            model_name='accounttypemodel',
            name='Percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percent'),
        ),
        migrations.AlterField(
            model_name='accounttypemodel',
            name='Subaccount',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Subkonto - poprawny format: 000000', regex='^[0-9]{6}$')], verbose_name='Subaccount'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Birth_city',
            field=models.CharField(max_length=100, verbose_name='Birth city'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Birth_date',
            field=models.DateField(verbose_name='Birth day'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='City',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Created_employee',
            field=models.CharField(max_length=50, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='First_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Id_customer',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id customer'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Identification',
            field=models.CharField(max_length=9, verbose_name='Identification'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Kod pocztowy - poprawny format: 00-000', regex='^[0-9]{2}-[0-9]{3}$')], verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='Balance_after_operation',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance after operation'),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='Id_operation',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id operation'),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='Operation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Operation date'),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='Operation_employee',
            field=models.CharField(max_length=50, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='Type_operation',
            field=models.IntegerField(verbose_name='Type operation'),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='Value_operation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Value operation'),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='Country_code',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]{2}$')]),
        ),
    ]
