# Generated by Django 5.0.3 on 2024-04-30 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0010_alter_accountmodel_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='Postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^[0-9]{2}-[0-9]{3}$')], verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='Country_code',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Kod kraju - poprawny format: AA', regex='^[a-zA-Z]{2}$')]),
        ),
    ]
