# Generated by Django 5.0.3 on 2024-04-30 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0011_alter_customermodel_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttypemodel',
            name='Id_account_type',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]{1}-[0-9]{2}$')], verbose_name='Id account type'),
        ),
        migrations.AlterField(
            model_name='accounttypemodel',
            name='Subaccount',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^[0-9]{6}$')], verbose_name='Subaccount'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='Pesel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]{11}$')], verbose_name='PESEL'),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='Bank_number',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(regex='^[0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='parametermodel',
            name='Country_code',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]{2}$')]),
        ),
    ]
