# Generated by Django 5.0.3 on 2024-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0012_alter_accounttypemodel_id_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='Type_operation',
            field=models.IntegerField(choices=[('', '--------'), (1, 'Deposit'), (2, 'Withdrawal')], verbose_name='Type operation'),
        ),
    ]
