# Generated by Django 5.0.3 on 2024-07-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0013_alter_operationmodel_type_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='Type_operation',
            field=models.IntegerField(choices=[('', '--------'), (1, 'Deposit'), (2, 'Withdrawal'), (3, 'Interest')], verbose_name='Type operation'),
        ),
    ]
