# Generated by Django 5.0.3 on 2024-08-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0014_alter_operationmodel_type_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='Address',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='Street',
            field=models.CharField(default='Klonowa', max_length=100, verbose_name='Street'),
            preserve_default=False,
        ),
    ]
