# Generated by Django 5.0.3 on 2024-08-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0015_remove_customermodel_address_customermodel_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='Apartment',
            field=models.CharField(blank=True, max_length=10, verbose_name='Apartment'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='House',
            field=models.CharField(default='10', max_length=10, verbose_name='House'),
            preserve_default=False,
        ),
    ]
