# Generated by Django 5.0.3 on 2024-08-23 16:39

import minibankapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0016_customermodel_apartment_customermodel_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='Free_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[minibankapp.validators.validator_free_balance], verbose_name='Free balance'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='Number_IBAN',
            field=models.CharField(blank=True, max_length=28, validators=[minibankapp.validators.validator_number_iban], verbose_name='IBAN number'),
        ),
    ]
