# Generated by Django 5.0.3 on 2024-09-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minibankapp', '0019_rename_date_log_logmodel_date_log_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logmodel',
            old_name='action_log',
            new_name='Action_log',
        ),
        migrations.RenameField(
            model_name='logmodel',
            old_name='data_log',
            new_name='Data_log',
        ),
        migrations.RenameField(
            model_name='logmodel',
            old_name='duration_log',
            new_name='Duration_log',
        ),
        migrations.RenameField(
            model_name='logmodel',
            old_name='function_log',
            new_name='Function_log',
        ),
        migrations.RenameField(
            model_name='logmodel',
            old_name='status_log',
            new_name='Status_log',
        ),
        migrations.RenameField(
            model_name='logmodel',
            old_name='user_log',
            new_name='User_log',
        ),
    ]
